source 'https://rubygems.org'
gem 'jekyll'
gem 'jekyll-locale', git: 'https://github.com/hellcp/jekyll-locale.git', ref: '1a9ba57'
gem 'jekyll-theme-opensuse', git: 'https://github.com/opensuse/jekyll-theme.git'
gem 'webrick'
